# Generated by Django 5.2.8 on 2025-12-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('asset_manager', 'Asset Manager'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
