# Generated by Django 5.2.7 on 2025-12-05 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_status'),
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrequest',
            name='requested_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='assets.asset'),
        ),
    ]
